config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :email_downcase
  validates :name, presence: true, length: {maximum: Settings.user.max_name_size}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.user.max_email_size}, format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: Settings.user.mini_password}

  private

  def email_downcase
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "Hello, world!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper 
  
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      log_in user
      redirect_to user
    else 
      flash.now[:danger] = t ".require_login"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user= User.find_by id: params[:id]
    if @user.nil?
      flash[:danger] = t ".user_not_found"
      redirect_to root_path
    end
  end

  def create
    @user = User.new user_params
    if @user.save 
      log_in @user
      flash[:success] = t ".welcome"
      redirect_to @user
    else 
      flash[:danger] = t ".failed" 
      render :new 
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = " "
    base_title = t ".ror_tutorial"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
   def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the" %> <%=link_to t(".ror_tutorial"), "http://www.railstutorial.org/" %>
    <%= t ".by" %> <%= link_to t(".author"), "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
      <li><%= link_to t(".new"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".user"), "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".Profile"), current_user %></li>
              <li><%= link_to t(".settings"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> <%= t ".ror_tutorial" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="eror_explanation">
    <div class="alert alert-danger">
      <%= t ".the_form" %> <%= pluralize(@user.errors.count, t(".error")) %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, t(".about_title") %>
<h1><%= t ".about" %></h1>
<p>
  <%= t ".the" %> <em><%= link_to t(".ror_tutorial"), "http://www.railstutorial.org/" %></em>
  <%= link_to t(".book"), "http://www.railstutorial.org/book" %><%= t(".and_to_teach") %>
  <%= link_to t(".screencast_series"), "http://screencasts.railstutorial.org/" %>
  <%= link_to t(".ruby_on"), "http://rubyonrails.org/" %>
  <%= t ".this_is" %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".contact_title") %>
<h1><%= t ".contact" %></h1>
<p>
  <%= t ".contact_at" %>
  <%= link_to t(".contact_page"), "http://www.railstutorial.org/contact" %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".help_title") %>
<h1><%= t ".help" %></h1>
<p>
  <%= t ".get_help_on" %>
  <%= link_to t(".rails_tutorial"), "http://www.railstutorial.org/help" %>
  <%= t ".get_help_sample_app" %>
  <%= link_to t(".ruby_on"), "http://www.railstutorial.org/book" %> <%= t ".book" %>
</p>

app/views/static_pages/home.html.erb
<% provide :title, t(".home_title") %>
<div class="center jumbotron">
  <h1><%= t ".welcome" %></h1>
  <h2>
    <%= t ".this_is" %>
    <%= link_to t(".ruby_on"), "http://www.railstutorial.org/" %>
    <%= t ".samapp" %>
  </h2>
  <%= link_to t(".sign_up_now"), signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), "http://rubyonrails.org/" %>
<%= link_to image_tag("kitten.jpg", alt: "A Cat") %>

app/views/users/new.html.erb
<% provide :title, t(".signup_title") %>
<h1><%= t ".sign_up" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, t(".confirm") %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit t(".create"), class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>